"""make_admin_fields_optional

Revision ID: dffec56257a2
Revises: 8adb9fe323f1
Create Date: 2026-01-10 01:25:02.887714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffec56257a2'
down_revision: Union[str, Sequence[str], None] = '8adb9fe323f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.alter_column('administrators', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('administrators', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('administrators', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('administrators', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('administrators', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('administrators', 'full_name')
    # ### end Alembic commands ###
